"""
Pydantic schemas for MongoDB documents — Log and Alert.
"""
from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field
import uuid


SeverityLevel = Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
ThreatType = Literal[
    "brute_force",
    "lateral_movement",
    "data_exfiltration",
    "command_and_control",
    "false_positive",
    "benign",
]
LayerType = Literal["network", "endpoint", "application"]


class LogDocument(BaseModel):
    """Normalized log event stored in MongoDB."""
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str
    layer: LayerType
    source_ip: str
    dest_ip: Optional[str] = None
    event_type: str
    username: Optional[str] = None
    bytes: int = 0
    status: Optional[str] = None
    extra: Dict[str, Any] = {}
    raw: Dict[str, Any] = {}
    ingested_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AlertDocument(BaseModel):
    """Threat alert generated by the detection engine."""
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    threat_type: ThreatType
    severity: SeverityLevel
    confidence: float = Field(ge=0.0, le=1.0)

    # Human-readable explanation
    explanation: str

    # Playbook mitigation steps
    playbook: List[str] = []

    # Contributing event IDs (cross-layer correlation)
    event_ids: List[str] = []

    # Source details
    source_ip: Optional[str] = None
    layers_involved: List[LayerType] = []

    # Timestamps
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    first_seen: Optional[str] = None
    last_seen: Optional[str] = None

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}
